### PR TITLE
Adding new examples

### PR DESCRIPTION
**Pull request by goran-mahovlic**

### CODE REVIEW

**Comment by trabucayre** [comment]
LGTM. Just a remark: you have copied pictures from colorBar. Maybe removing or adding new one may be more relevant.
Is it necessary to add colognechip evb support since there is no ps2 connector?

**Comment by goran-mahovlic** [comment]
Well preserving all board constrains is ok - but they may also have some folder in root so we do not have them in every repo?

Yes updated README would be good to have , also pictures could be in root so you can have cleaner repo :)

**Comment by trabucayre** [comment]
I think pictures are correctly placed (to illustrate a specific demonstration on various boards), In fact for your demonstrations it make sense to replace pictures by new one adapted to this demo.

**Comment by trabucayre** [comment]
Applied manually with small cleanup/nitpick.
Thanks @goran-mahovlic !

**Pull request closed without merging**
